---
- name: Update APT
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: False

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ispconfig_base_packages }}"
